-- Notifications generated by the deadline-checking scheduler.
-- Unique constraint on (user_id, task_id, type, due_date_snapshot) ensures
-- the scheduler can run repeatedly without creating duplicate notifications
-- for the same event occurrence.

CREATE TABLE notifications (
    id                  BINARY(16)      NOT NULL,
    user_id             BINARY(16)      NOT NULL,
    task_id             BINARY(16)      NOT NULL,
    type                VARCHAR(20)     NOT NULL,
    title               VARCHAR(255)    NOT NULL,
    message             TEXT            NOT NULL,
    is_read             TINYINT(1)      NOT NULL DEFAULT 0,
    due_date_snapshot   DATE            NOT NULL,
    read_at             TIMESTAMP       NULL,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT chk_notifications_type CHECK (type IN ('DEADLINE_SOON', 'DUE_TODAY', 'OVERDUE')),
    -- Idempotency: one notification per (user, task, type, due_date_snapshot)
    CONSTRAINT uq_notifications_key UNIQUE (user_id, task_id, type, due_date_snapshot),
    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_notifications_task
        FOREIGN KEY (task_id) REFERENCES tasks (id)
        ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- Primary query: fetch all notifications for a user ordered newest-first
CREATE INDEX idx_notifications_user_created ON notifications (user_id, created_at DESC);

-- Scheduler: find unread notifications for a given user
CREATE INDEX idx_notifications_user_read ON notifications (user_id, is_read);
